language: python
jobs:
  include:
    - name: "Linux 3.6"
      python: 3.6
    - name: "Linux 3.7"
      python: 3.7
    - name: "Linux 3.8"
      python: 3.8

install:
  - pip3 install .
script: pytest