language: python
jobs:
  include:
    - name: "Linux 3.6"
      python: 3.6
    - name: "Linux 3.7"
      python: 3.7
    - name: "Linux 3.8"
      python: 3.8
    - name: "Windows 3.8"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install .
script: pytest